#!/bin/bash

PGPASSWORD="mysecretpassword"

sudo docker run -it --link postgrestest_app_1:postgres --rm -e PGPASSWORD=$PGPASSWORD postgres /bin/bash -c 'pg_dumpall -h "$POSTGRES_PORT_5432_TCP_ADDR" -p "$POSTGRES_PORT_5432_TCP_PORT" -U postgres' > $1/backup.sql
